version: '3.4'
services:
  fastapi-simple-auth:
    container_name: fastapi-basic-auth
    labels:
      description: Simple auth FastAPI
    ports:
      - "8000:8000"
    build: .
    env_file:
      - .env